#!/usr/bin/env Rscript

###


# Title: visualize_PhyloTree_base.R
# Date: 2023.01.31
# Author: Virág Varga
#
# Description:
#   This program visualizes an input Newick tree, and outputs the results to an
#       SVG file.
#
# List of functions:
#   No functions are defined in this script.
#
# List of standard and non-standard modules used:
#   tools
#   ape
#   svglite
#   tidyverse
#   viridis
#
# Procedure:
#   1. Load necessary libraries; determine inputs & outputs
#   2. Extract species information in order to color the tree tip labels.
#   3. Visualize the phylogenetic tree
#   4. Write out results to file
#
# Known bugs and limitations:
#   - There is no quality-checking integrated into the code.
#   - The output file name is not entirely user-defined, but is instead based on the input
#       file name plus a user-provided extension.
#   - Note that the input gene names need to be in the NCBI BLAST format. The editing
#       of species names also assumes the input tree was generated by IQ-TREE.
#
# Usage:
#   Edit the file names & paths before running this script from within RStudio.
#
# This script was written for R 4.2.2, in RStudio 2022.12.0+353 "Elsbeth Geranium".


###


# Part 1: Load necessary libraries; determine inputs & outputs

# setting up the workspace
# clear the environment
rm(list = ls())
# set working directory
setwd("SET/THE/PATH/TO/YOUR/WORKING/DIRECTORY/HERE")
# Windows users, your file path should probably start with something like: C:/Users/USERNAME/Documents/ETC/ETC/ETC


# load libraries
library(tools)
library(ape)
library(svglite)
library(tidyverse)
library(viridis)


# Provide the input tree file
tree_file <- "FILENAME.treefile"

# Determine the output file name from the input file name
usr_file_ext <- "Vis"
# strip the file extension
# ref: https://stackoverflow.com/questions/29113973/get-filename-without-extension-in-r
tree_base <- file_path_sans_ext(basename(tree_file))
out_base <- paste(tree_base, usr_file_ext, sep = "_")

# ref: https://www.rdocumentation.org/packages/svglite/versions/2.1.0/topics/svglite
svglite(paste(out_base, "svg", sep = "."), width = 30, height = 40)


# Part 2: Extract species information in order to color the tree tip labels

# read in the tree using the ape library
# ref: https://cran.r-project.org/web/packages/TreeTools/vignettes/load-trees.html
spp_tree <- read.tree(tree_file)

# get the tree tip labels into a list (vector)
gene_list <- spp_tree$tip.label
# now extract the species IDs from the list
for (i in 1:length(gene_list)) {
  # iterate over the elements in the list
  # and save the actual gene ID to a variable in each iteration of the loop
  gene_id <- gene_list[i]
  # split the gene in gene_id into a list based on the location of "__"s
  gene_id_list <- str_split(gene_id, "__")
  # get the last element of the list (i.e., the species name)
  species_id <- sapply(gene_id_list, tail, 1)
  # finally, remove the trailing "_"
  species_id <- str_sub(species_id, end = -2)
  # add species IDs to a species list
  if (!exists("species_list")) {
    # check if the list already exists
    # if not, initialize the list with the first species ID
    species_list <- c(species_id)
  } else {
    # if the species_list variable exists, append the species ID
    species_list <- append(species_list, species_id)
  }
}

# connect gene names with species IDs by writing the lists to a dataframe
species_df <- data.frame(
  Gene_IDs = gene_list,
  Species_IDs = species_list
)

# count the number of unique species/stains
spp_num <- length(unique(species_df$Species_IDs))
# generate vector of hex codes matching number of unique species/strains
color_list <- viridis(spp_num)
# write the list of unique species IDs to a list
uniq_spp <- unique(species_df$Species_IDs)
# create a dataframe of species/strains to colors
color_df <- data.frame(
  Spp_Unique = uniq_spp,
  Color_Assoc = color_list
)

# add an empty column to species_df
species_df <- add_column(species_df, Spp_Color = NA)
# now fill in the color information
for (j in 1:length(species_df$Species_IDs)) {
  # iterate over the species IDs
  # with each iteration, save the ID to variable j_spp
  j_spp <- species_df$Species_IDs[j]
  for (k in 1:length(color_df$Spp_Unique)) {
    # iterate over the color dataframe
    # and save the species ID to variable k_spp
    k_spp <- color_df$Spp_Unique[k]
    # and check whether the species IDs match between the two dataframes
    if (j_spp == k_spp) {
      # if the species IDs match
      # replace the NA in the species dataframe with the associated color
      species_df$Spp_Color[j] <- color_df$Color_Assoc[k]
    }
  }
}


# Part 3: Visualize the phylogenetic tree

# plot the base tree with the colored tip labels
plot(spp_tree, tip.color = species_df$Spp_Color)


# Part 3: Write out results to file
dev.off()
